### PR TITLE
Dmsp clean bugfix

### PR DESCRIPTION
**Pull request by aburrell**
Fixed bug where no cleaning removed all data instead of returning all data.

### CODE REVIEW

**Comment by rstoneback** [comment]
I’m just seeing this over email. I thought the download tests ensured there was some data after loading with no cleaning applied. I’m curious why we didn’t catch this earlier

Cheers,
Russell

On Mar 1, 2019, at 5:42 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


@jklenzing approved this pull request.

Looks good, dmsp tests pass locally.

**Comment by rstoneback** [comment]
The cleaning routine isn't called if clean_level is none.

Line 373 could be made an error.

**Comment by aburrell** [comment]
@rstoneback , the only thing I can think of is that the tests don't look for all the different dmsp tags and sat ID's.

**Comment by aburrell** [comment]
Do we want to do something with line 373 or merge?

**Comment by jklenzing** [comment]
I was largely wondering if that line would produce the same error as above.  If so, we should fix it now.

**Comment by aburrell** [comment]
It depends on the purpose of that line.  That bit is Russell's code, but reading it I think it should be replaced.  I also just checked the rest of the instruments (using the idx variable name) and found some to be fixed.

**Comment by rstoneback** [comment]
Going from memory if the rpa flag isn’t in the  loaded file then that routine drops all the data.

This behavior is noted in docstring but a warning or error could be more appropriate. I can imagine someone trying to figure out why there is no data coming out of their dmsp pipeline.

On Mar 4, 2019, at 7:33 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


It depends on the purpose of that line. That bit is Russell's code, but reading it I think it should be replaced. I also just checked the rest of the instruments (using the idx variable name) and found some to be fixed.

**Comment by aburrell** [comment]
Do we want the routine to drop all the data if there isn't an rpa flag, or keep it all?

**Comment by rstoneback** [comment]
I believe the rpa flag is used by the routine so I think we should have a safe default. Either no data or more explicit warning.

My vote is no data.

On Mar 4, 2019, at 7:45 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:

Do we want the routine to drop all the data if there isn't an rpa flag, or keep it all?

**Comment by rstoneback** [comment]
Is the empty list not working as a mechanism for dropping data?

**Comment by aburrell** [comment]
It is working as a mechanism for dropping data.  That wasn't the behaviour I was expecting when using it though, so that is why there were problems.

**Comment by rstoneback** [comment]
Thanks for clearing that up.

**Pull request merged**
