### PR TITLE
Supermag download

### PR DESCRIPTION
**Pull request by jklenzing**
Addresses #222.

Supermag no longer supports download via script.  Removing `download` routine and replacing with warning message to direct users to download site, similar to champ_star.

Also updated docstring and supported keywords in `list_remote_files` for consistency.

### CODE REVIEW

**Comment by rstoneback** [comment]
I don't want to delete the code. I do like the warning though. Perhaps we should rename the original download method in hopes that SuperMAG will do better in the future.

**Comment by jklenzing** [comment]
We can always pull the code back from an earlier commit.  I don't like removing this, but it comes down to ~200 lines of unused, untested code.  Since we can't do end-to-end testing on supermag, we've already lost most of the coverage on this file (80% down to 13%), and total coverage is back below 80%.

We could also comment it out, which in general we have been trying to avoid in previous pull requests.  @aburrell?

**Comment by jklenzing** [comment]
There's a version up now where the old download routine is maintained as `test_download`, in case we want to test the downloads in the future.  Code coverage drops 0.8% to 77.47%.

**Comment by rstoneback** [comment]
So it goes with testing coverage.

I think our download warning text should be stronger. SuperMAG made a choice to block downloads.

“SuperMAG and the Johns Hopkins Applied Physics Laboratory have chosen to block downloads using any tool other than the website (http://supermag.jhuapl.edu) and direct human interaction. “

Could add “ Please contact the National Science Foundation (find sponsor email) if you disagree with restricted access for public data.” Once I find the correct program /officer email.

On May 28, 2019, at 2:17 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


There's a version up now where the old download routine is maintained as test_download, in case we want to test the downloads in the future. Code coverage drops 0.8% to 77.47%.

**Comment by jklenzing** [comment]
I think that until we have more info, the current warning is sufficient.  We should get this merged to fix the unit tests for now.

**Comment by rstoneback** [comment]
That’s fine.


On May 28, 2019, at 4:29 PM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


I think that until we have more info, the current warning is sufficient. We should get this merged to fix the unit tests for now.

**Pull request merged**
