### PR TITLE
Update sw_f107.py

### PR DESCRIPTION
**Pull request by aburrell**
Bug for new downloads, because there is never enough testing.

### CODE REVIEW

**Comment by aburrell** [comment]
Feel free to review Jeff, but I will test this once more locally tomorrow to be sure it works as intended with incremental updates to existing files.

**Comment by jklenzing** [comment]
Don’t see anything out of place here. Will wait for local tests as this is hidden from the Eye of Travis.

**Comment by aburrell** [comment]
And NOAA is still down.

**Comment by aburrell** [comment]
Ok @jklenzing, local success on day two.  Give it a go.

**Pull request merged**
