### PR TITLE
fixed the get_duplicates future warning

### PR DESCRIPTION
**Pull request by silviolleite**
It is updated to fix the future warning about the get_duplicates() function. This function is deprecated and will be removed in a future release.

### CODE REVIEW

**Comment by silviolleite** [comment]
The coverage problem isn't my code. Can you help me how fix this problem?

**Comment by aburrell** [comment]
The coverage is probably a python2/3 issue.  Python 2 has more coverage since certain tests need to be skipped in python 3 (pyglow doesn't work in python 3).  Because of this, the coverage will change based on whether the tests for python 2 finish before or after the tests for python 3.  Don't worry about this problem.

**Comment by silviolleite** [comment]
Okay, Thanks!

**Comment by rstoneback** [comment]
Closing #62 with the merge of this pull.

**Pull request merged**
