### PR TITLE
Omni steadiness

### PR DESCRIPTION
**Pull request by aburrell**
Added custom functions to OMNI HRO instrument that calculate the clock angle, IMF magnitude in the Y-Z plane, and calculate the length of time the IMF is steady.

### CODE REVIEW

**Comment by aburrell** [comment]
Test the circular statistics:

import pysat
import datetime as dt
import numpy as np
import pandas as pds
from scipy import stats

test_angles = [340.0, 348.0, 358.9, 0.5, 5.0, 9.87]
ref_mean = stats.circmean(test_angles, high=360.0, low=0.0)
ref_std = stats.circstd(test_angles, high=360.0, low=0.0)
test_mean = pysat.instruments.omni_hro.nan_circmean(test_angles, high=360.0, low=0.0)
test_std = pysat.instruments.omni_hro.nan_circstd(test_angles, high=360.0, low=0.0)

print(ref_mean, test_mean, ref_std, test_std)
357.070911054 357.070911054 10.1422650414 10.1422650414

test_angles.append(np.nan)
ref_mean = stats.circmean(test_angles, high=360.0, low=0.0)
ref_std = stats.circstd(test_angles, high=360.0, low=0.0)
test_mean = pysat.instruments.omni_hro.nan_circmean(test_angles, high=360.0, low=0.0)
test_std = pysat.instruments.omni_hro.nan_circstd(test_angles, high=360.0, low=0.0)

print(ref_mean, test_mean, ref_std, test_std)
nan 357.070911054 nan 10.1422650414

**Comment by aburrell** [comment]
Testing clock angle calculation:

inst = pysat.Instrument(platform="omni", name='hro', tag='1min', pad=pds.DateOffset(1))
ttime = dt.datetime(2000,9,1)
inst.download(ttime-dt.timedelta(days=1), ttime+dt.timedelta(days=1))
inst.custom.add(pysat.instruments.omni_hro.calculate_clock_angle, kind='modify')
inst.custom.add(pysat.instruments.omni_hro.calculate_imf_steadiness, kind='modify')
inst.load(date=ttime)

Initializing three day/file window
No omni hro 1min data for 08/31/00
Returning omni hro 1min data for 09/01/00
Returning omni hro 1min data for 09/02/00

test_angle = np.arctan2(inst['BY_GSM'], inst['BZ_GSM']

print np.degrees(test_angle)[-10:], "\n", inst['clock_angle'][-10:]
2000-09-01 23:50:00    109.860558
2000-09-01 23:51:00    101.403801
2000-09-01 23:52:00     93.179825
2000-09-01 23:53:00     87.442093
2000-09-01 23:54:00    100.677879
2000-09-01 23:55:00   -158.629379
2000-09-01 23:56:00     52.125011
2000-09-01 23:57:00    111.464935
2000-09-01 23:58:00    132.696686
2000-09-01 23:59:00    134.309723
Name: BY_GSM, dtype: float32 
2000-09-01 23:50:00    109.860558
2000-09-01 23:51:00    101.403801
2000-09-01 23:52:00     93.179825
2000-09-01 23:53:00     87.442093
2000-09-01 23:54:00    100.677879
2000-09-01 23:55:00    201.370621
2000-09-01 23:56:00     52.125011
2000-09-01 23:57:00    111.464935
2000-09-01 23:58:00    132.696686
2000-09-01 23:59:00    134.309723
Name: clock_angle, dtype: float32

test_mag = np.sqrt(inst['BY_GSM']**2 + inst['BZ_GSM']**2
print test_mag[-10:], "\n", inst['BYZ_GSM'][-10:]
2000-09-01 23:50:00    2.796319
2000-09-01 23:51:00    3.590891
2000-09-01 23:52:00    3.244996
2000-09-01 23:53:00    2.912902
2000-09-01 23:54:00    3.022333
2000-09-01 23:55:00    0.246982
2000-09-01 23:56:00    0.456070
2000-09-01 23:57:00    4.427053
2000-09-01 23:58:00    5.102362
2000-09-01 23:59:00    4.695530
dtype: float32 
2000-09-01 23:50:00    2.796319
2000-09-01 23:51:00    3.590891
2000-09-01 23:52:00    3.244996
2000-09-01 23:53:00    2.912902
2000-09-01 23:54:00    3.022333
2000-09-01 23:55:00    0.246982
2000-09-01 23:56:00    0.456070
2000-09-01 23:57:00    4.427053
2000-09-01 23:58:00    5.102362
2000-09-01 23:59:00    4.695530
Name: BYZ_GSM, dtype: float32

**Comment by aburrell** [comment]
Testing IMF steadiness (plot):

import matplotlib as mpl
import matplotlib.pyplot as plt

igood = [i for i,s in enumerate(inst.data['IMF_Steady']) if s >= 10]
byz_mean = inst['BYZ_GSM'].rolling(min_periods=12, window=15, center=True).mean()
ca_mean = inst['clock_angle'].rolling(min_periods=12, window=15, center=True).apply(pysat.instruments.omni_hro.nan_circmean, kwargs={"high":360.0, 'low':0.0})

f = plt.figure()
ax = f.add_subplot(2,1,1)
ax.errorbar(inst.data.index, byz_mean, yerr=inst.data['BYZ_CV'], fmt='.', color='0.6')
ax.set_ylim(0,7)
ax.set_xlim(dt.datetime(2000,9,1,5), dt.datetime(2000,9,1,7))
ax.set_ylabel(r"|B$_{YZ}$| (nT)")
ax.xaxis.set_major_formatter(mpl.dates.DateFormatter("%H:%M"))
ax.plot(inst.data.index, inst.data['BYZ_GSM'], ".", color="k", ms=2)
ax.plot(inst.data.index[igood], inst.data['BYZ_GSM'][igood], ".", color="dodgerblue", ms=2)

ax = f.add_subplot(2,1,2)
ax.errorbar(inst.data.index, ca_mean, yerr=inst.data['clock_angle_std'], fmt='.', color='0.6')
ax.set_ylim(0,360)
ax.set_xlim(dt.datetime(2000,9,1,5), dt.datetime(2000,9,1,7))
ax.xaxis.set_major_formatter(mpl.dates.DateFormatter("%H:%M"))
ax.yaxis.set_major_locator(mpl.ticker.MultipleLocator(45))
ax.set_xlabel("Universal Time (hours of {:s})".format(ttime.strftime("%d %b %Y")))
ax.set_ylabel(r"$\theta$ ($^\circ$)")
ax.plot(inst.data.index, inst.data['clock_angle'], ".", color="k", ms=2)
ax.plot(inst.data.index[igood], inst.data['clock_angle'][igood], ".", color="dodgerblue", ms=2)

f.suptitle("Clock Angle Steadiness Test", fontsize="medium")
ax.legend(["All", r"CV$_{|B_{YZ}|} \leq$ 0.5 and $\sigma_\theta \leq 28.6^\circ$ for $\geq$ 10 min", "Mean and CV/$\sigma$"], loc=1, ncol=1, fontsize="xx-small", markerscale=2, labelspacing=.1, handlelength=1)

f.savefig("steadiness_test.png")

clock_angle_1sept2000_sigma_test_thresh_fix_timing_zoom

**Comment by aburrell** [comment]
@rstoneback I'm having trouble with three of the tests.  I'm trying to use a test instrument instance (copied from earlier in test_custom.py), but it has no data.  Not sure how to get it to have data.

**Comment by rstoneback** [comment]
@aburrell
Can you put the omni tests in a new file, say test_omni_hro.py ? Nosetests looks for and runs anything with test in the name. It (test_omni_hro.py) should be added automatically to unit test runs though sometimes nosetests doesn’t pick up files as expected.


On Mar 7, 2018, at 5:57 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


@rstoneback<https://github.com/rstoneback> I'm having trouble with three of the tests. I'm trying to use a test instrument instance (copied from earlier in test_custom.py), but it has no data. Not sure how to get it to have data.

**Comment by aburrell** [comment]
I can do that.  

One thing though, I did create test data, but set the shape to be the shape of the index (I assumed the index would be non-zero).  Since that’s clearly not true, do I need to create fake times as well for the index?  Or is it ok to skip that?

**Comment by rstoneback** [comment]
pysat_testing.py generates time index data. I didn't see your commands to generate the test data when I last looked. Can you direct me?


On Mar 7, 2018, at 10:10 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:

I can do that.

One thing though, I did create test data, but set the shape to be the shape of the index (I assumed the index would be non-zero). Since that’s clearly not true, do I need to create fake times as well for the index? Or is it ok to skip that?

**Comment by aburrell** [comment]
I’ve figured it out now.  Maybe this next Travis CI test will even pass :-P

**Comment by aburrell** [comment]
Well, that was a learning experience!  @rstoneback , @jklenzing , feel free to run any of the tests outlined here and merge when satisfied.

**Pull request merged**
