### PR TITLE
Reorganize instrument methods

### PR DESCRIPTION
**Pull request by jklenzing**
Addresses #206.

Moves the four instrument methods files to the `instruments.methods` directory.  Updates all calls to methods files in instruments and documentation.

### CODE REVIEW

**Comment by aburrell** [comment]
I approve of Jeff naming suggestion.

**Comment by jklenzing** [comment]
This branch will need updates so that testing_methods follows new conventions after #203 is merged.

**Comment by rstoneback** [comment]
This is looking good. Any other changes coming down the pipe?

**Comment by rstoneback** [comment]
For the testing the only failures I see are related to SuperMAG downloads.

**Comment by jklenzing** [comment]
Just merged the changes from develop. Once it’s green, it’s ready to go.

**Comment by jklenzing** [comment]
Ready for final review

**Pull request merged**
