### PR TITLE
Develop update

### PR DESCRIPTION
**Pull request by aburrell**
Update models branch to include changes to develop branch.

### CODE REVIEW

**Comment by rstoneback** [comment]
Great to see your model code come up again in a pull. The direction seems backward though, pulling develop into model?  The last commit pushed model into develop.

**Comment by aburrell** [comment]
The model branch still needs some major updates before it's ready for develop, I think.  Adding testing to the new routines, for a start.  I want to make sure it stays close to the develop branch so that when it goes in there aren't a lot of conflicts.

**Comment by rstoneback** [comment]
Fair enough, just pointing out your last commit merged model into develop.

**Comment by aburrell** [comment]
Yeah... I should probably feel better about putting incremental changes from model into develop.  I'll try and build it up to that point soon.

**Comment by rstoneback** [comment]
You should feel better about it. I have no reservations about including your work in develop. I was ready to merge model in the last time you had a pull from develop into model. It is the source of my confusion as to the direction of the pull. You are working on cool stuff and the model pull isn't a small one. Okay with me (appropriate even) to spread things out. 

I am in full agreement about tests and the like, but it is a process. Unit tests are good, but actually working with the code on problems is a great test itself. In this case in particular, you are adding new areas to pysat, so the immediate requirement for complete test coverage is lower. I am biased, perhaps, as I personally want to use the model stuff with the TIEGCM work I'm doing.

One day, perhaps pysat will be established enough that ultra standards could be applied to pulls from core developers. In the meantime, I don't want metrics like code coverage percentages to stop your progress in develop. Your influence is already all over pysat. Why stop now? :)

**Pull request merged**
