### PR TITLE
Update of cosmic downloads with requests

### LINKED ISSUE #64: CDAAC data access
This affects COSMIC data:

> Dear CDAAC Users, 
> 
> Please note our Webpage now uses Secure Socket Layer (SSL) and thus it starts with https:// instead of http://
> https://cdaac-www.cosmic.ucar.edu/cdaac/index.html
> 
> We have added a redirect from http:// to https://, so your bookmarks should just redirect. 
> However if you have any scripts that fetch data with http, please change your scripts to use https://

### PR DESCRIPTION
**Pull request by jklenzing**
Closes #64 and #146.

Summary of changes
- Updates `cosmic` and `cosmic2013` download routines with `requests` (#146)
- Switch to HTTPS download (#64)
- update variable names in `cdaweb_methods` for consistency
- pep8 and style scrub

### CODE REVIEW

**Comment by jklenzing** [comment]
Notes:
- Since cosmic and cosmic2013 are skipped in Travis tests, please verify locally.  Working well with Python 3.6.

**Comment by jklenzing** [comment]
Ready for review.

**Comment by jklenzing** [comment]
Code snippet for local check:

```
import pysat
start = pysat.datetime(2009, 1, 1)
stop = start
cosmic = pysat.Instrument(platform='cosmic', name='gps', tag='ionprf')   
cosmic.download(start,stop, user=user, password=password)  
cosmic = pysat.Instrument(platform='cosmic2013', name='gps', tag='ionprf')   
cosmic.download(start,stop, user=user, password=password)

**Comment by aburrell** [comment]
The tests worked for me.

**Pull request merged**
