### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by rstoneback**

### CODE REVIEW

**Comment by rstoneback** [comment]
I agree totally. My thought was perhaps pysat@utdallas.edu. 

The downside is I requested an additional account for the SuperMag data from UTD and it never actually came through.

The other option is I (startup) could pay for a hosted web server with email and issue pysat.org email addresses.

**Comment by aburrell** [comment]
I think not tying it to UTD would be a good thing.  I'd be cheap and do gmail or another free service, but whatever works.

**Comment by rstoneback** [comment]
created account pysat.developers@gmail.com . Not allowed to have just pysat, too short.

**Comment by aburrell** [comment]
I'll merge once the checks are complete.

**Comment by rstoneback** [comment]
Great. Thanks.

**Comment by aburrell** [comment]
So.... Any idea what's up with Travis?

**Comment by rstoneback** [comment]
The only change compared to master is the code of conduct. It doesn’t have the cache or other fixes from the build_fix branch. 

This is my guess. Haven’t actually looked.... in final prep before my seminar.

**Comment by aburrell** [comment]
Good luck!

Since Travis blocks merging, we'll need to get this fixed before the code of conduct can be added.

**Comment by aburrell** [comment]
Ok, looking more closing at things that failed, I think I figured out what it is.

1) $pyglow_dir is never defined in the travis-ci
2) These lines:

`export PYGLOW_SIZE=$(du -s $pyglow_dir);
      echo $PYGLOW_SIZE;
      echo 'PYGLOW_SIZE';
      export CHECK_SIZE="50000";
      if [["$PYGLOW_SIZE" -lt "$CHECK_SIZE"]]; then
        rm -r ./pyglow;
        echo 'removing pyglow directory';
      fi
`
should probably be:

`export PYGLOW_SIZE=($(du -s $pyglow_dir));
      echo 'PYGLOW_SIZE' $PYGLOW_SIZE;
      export CHECK_SIZE=50000;
      if [[ "${PYGLOW_SIZE}" -lt "$CHECK_SIZE" ]]; then
        rm -r $pyglow_dir;
        echo 'removing pyglow directory';
      fi
`

**Comment by rstoneback** [comment]
Thanks for taking a look.

I forgot to mention that pyglow_dir is set in the travis CI settings.

To make things a bit more confusing, the master build passed, even though the pyglow script lines were all wonky.

**Comment by rstoneback** [comment]
The whole system might need a few minutes to think about what it has done. :)

The Travis folks may turn on the troubleshooting button and give us some better tools to sort this issue out.

**Comment by aburrell** [comment]
Improvement(ish):

3.6 failed in the DMSP_IVM download test.  

> ======================================================================
> ERROR: Checking download routine functionality for module:  dmsp ivm utd f14
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
>     self.test(*self.arg)
>   File "/home/travis/build/rstoneback/pysat/pysat/tests/test_instruments.py", line 236, in check_download
>     raise e
>   File "/home/travis/build/rstoneback/pysat/pysat/tests/test_instruments.py", line 215, in check_download
>     inst.download(start, start)
>   File "/home/travis/build/rstoneback/pysat/pysat/_instrument.py", line 960, in download
    **kwargs)
>   File "/home/travis/build/rstoneback/pysat/pysat/instruments/dmsp_ivm.py", line 174, in download
>     '--kindat='+str(madrigal_tag[sat_id])])
>   File "/home/travis/miniconda/envs/test-environment/lib/python3.6/subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "/home/travis/miniconda/envs/test-environment/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['globalDownload.py', '--verbose', '--url=http://cedar.openmadrigal.org', '--outputDir=/tmp/tmppwycd_ih/dmsp/ivm/utd/', '--user_fullname=pysat_testing', '--user_email=pysat_testing@not_real_email.org', '--user_affiliation=pysat', '--format=hdf5', '--startDate=01/02/1998', '--endDate=01/02/1998', '--inst=8100', '--kindat=10244']' returned non-zero exit status 1.

**Comment by rstoneback** [comment]
I restarted the testing and it passed. Ready for you to merge. Cheers.

**Pull request merged**
